### ISSUE TITLE
PHP Fatal error:  Class 'Efficiently\AuthorityController\AuthorityControllerServiceProvider' not found

### ISSUE THREAD

**Issue by neerajrepo1** [efficiently/authority-controller#16]
I tried installing authority-controller using the following steps
1. run command from my project root composer require efficiently/authority-controller:1.2.*
2. 'Efficiently\AuthorityController\AuthorityControllerServiceProvider', added in app/config/app.php
3. 'Params'    => 'Efficiently\AuthorityController\Facades\Params',
   'Authority' => 'Efficiently\AuthorityController\Facades\Authority',
  added in app/config/app.php under aliases array 
After that i run 
php artisan
then i get the following error
 PHP Fatal error:  Class 'Efficiently\AuthorityController\AuthorityControllerServiceProvider' not found in G:\wamp\www\laratest\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php on line 157

I am not sure what i am missing.

Any help?

**Comment by tortuetorche** [comment]
@neerajrepo1 If you have still this error, feel free to reopen this issue.
