### ISSUE TITLE
Laravel 5??

### ISSUE THREAD

**Issue by jccp2** [efficiently/authority-controller#17]
Any idea if this works on laravel 5

**Comment by tortuetorche** [comment]
Hi @jccp2, 

I plan to do this during the next weeks.
For the moment it doesn't work. 

Cheers,
Tortue Torche

**Comment by dailez** [comment]
I really like your package and I would love to see it work under laravel 5. Looking forward to your update.

**Comment by tortuetorche** [comment]
@dailez Thank you for your support.

I've started to update Authority-Controller to be compatible with Laravel 5.
Some tests aren't passing yet but I hope to release an alpha version next week.

Cheers,
Tortue Torche

**Comment by tortuetorche** [comment]
I make some good progress, now all tests pass !
I still need to update the installation instructions and the [Laravel demo](https://github.com/efficiently/laravel_authority-controller_app)

**Comment by jccp2** [comment]
@tortuetorche  thank you its an awesome package, I am new to laravel so im just getting to know the internals if not I would jump in and help. when its ready and you pushed it ill give it a try at least I can help you find bugs and fix what ever I can.

**Comment by tortuetorche** [comment]
Authority-Controller 2.0 now supports Laravel 5 !
It's an alpha release, so you need to tweak the `composer.json` file of your Laravel 5 application.
Add a `repositories` option:
```javascript
{
	//...
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/stayallive/authority"
		},
		{
			"type": "vcs",
			"url": "https://github.com/stayallive/authority-l5"
		}
	],
	//...
}
```
Then add these two options:
```javascript
{
	//...
	"prefer-stable": true,
	"minimum-stability": "dev"
}
```
Here a [composer.json sample](https://github.com/efficiently/laravel_authority-controller_app/blob/318d48ee42b8e63002d6d6a6cca34c868a63fb84/composer.json).

Feel free to reopen this issue if you have some problems with Authority-Controller 2.0.

**Comment by tortuetorche** [comment]
By the way, I also need to update the [Wiki docs](https://github.com/efficiently/authority-controller/wiki), so I plan to do this in a couple of weeks.

Have fun,
Tortue Torche.

**Comment by tortuetorche** [comment]
By the way, I also need to update the [Wiki docs](https://github.com/efficiently/authority-controller/wiki), so I plan to do this in a couple of weeks.

Have fun,
Tortue Torche.
