### ISSUE TITLE
The requested package efficiently/authority-controller could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by giwrgos88** [efficiently/authority-controller#18]
Trying to add your package into my laravel 5 project and i'm getting the following message when i'm trying to update the composer

  Problem 1
    - The requested package efficiently/authority-controller could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Can you help me please? Thank you

**Comment by giwrgos88** [comment]
I found the solution, I had to add this two lines on the bottom of the composer

	"prefer-stable": true,
	"minimum-stability": "dev"

like this https://github.com/efficiently/laravel_authority-controller_app/blob/318d48ee42b8e63002d6d6a6cca34c868a63fb84/composer.json

**Comment by tortuetorche** [comment]
Good catch, Authority-Controller 2.0 is still in an alpha version so you need to add these two lines in your `composer.json` file.
