### ISSUE TITLE
Authorizing controller actions are not working

### ISSUE THREAD

**Issue by giwrgos88** [efficiently/authority-controller#22]
Hello, when I'm adding the $this->loadAndAuthorizeResource(); inside on each constructor of each controller I'm getting the following error message
```
ReflectionException in Container.php line 776:
Class Dashboard does not exist
```

but when I'm removing the loadAndAuthorizeResource, the controller is working fine. If I add the loadAndAuthorizeResource inside the abstract class Controller which extends BaseController, is working but is not validating the user if has the roles to add, edit a post. How i can fix it? thank you

here is my authority 
```php
        $user = Auth::guest() ? new All4FX\Models\User : $authority->getCurrentUser();

        // Define abilities for the passed in user here. For example:
        if ($user->hasRole('Super Administrator'))
        {
            $authority->allow('manage', 'all');
        }
        else if ($user->hasRole('Editor'))
        {
            $authority->allow('read', 'all');
            $authority->allow('create', 'all');
        }
        else
        {
            $authority->allow('read', 'all');
        }
```

**Comment by tortuetorche** [comment]
Hi @giwrgos88,

Can you post your `DashboardsController` class, please?

Cheers,
TortueTorche

**Comment by giwrgos88** [comment]
<?php namespace APPPATH\Http\Controllers;
use Auth;
class DashboardController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Home Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders your application's "dashboard" for users that
	| are authenticated. Of course, you are free to change or remove the
	| controller as you wish. It is just here to get your app started!
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */

	public function __construct()
	{
        $this->middleware('auth');
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
        if(Auth::check()) {

            return view('admin.dashboard.index')->with('pages', Category::where('category_type', '=', 'pages')->count())->with('posts', Category::where('category_type', '=', 'posts')->count())->with('my_activity',$user_activity);
        }
        else
        {
            return redirect('/auth/login');
        }
	}

}

**Comment by tortuetorche** [comment]
Do you have a `Dashboard` model?

**Comment by giwrgos88** [comment]
@tortuetorche the dashboard doen't have it's own model but, the categories have. do you want me to send you the category controller and model?

**Comment by giwrgos88** [comment]
@tortuetorche the dashboard doesn't have it's own model but, the categories have. do you want me to send you the category controller and model?

**Comment by tortuetorche** [comment]
Your issue occurs on the Dashboard controller, on the Categories controller or on both?
For the Dashboard controller, Authority-Controller throws an error because it search a Dashboard model, but you can config the `loadAndAuthorizeResource()` method to use the Category model instead.

**Comment by giwrgos88** [comment]
I put the loadAndAuthorizeResource on the constructor of the CategoryController and I had the same issue. Each of my controllers are stored inside to folders, for example for the DashboardController.php is stored inside the Htttp/Controllers/Administrator/Dashboard and the CategoryController.php inside to Htttp/Controllers/Administrator/Category

From the message is look like that it takes the folder and makes it class?

**Comment by tortuetorche** [comment]
OK, can you tell me where is your Category model ?

**Comment by giwrgos88** [comment]
Yes is inside app/Models/Categories/Category.php
Here is the model

< ? php namespace APPPATH\Models\Categories;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Nicolaslopezj\Searchable\SearchableTrait;

/**
 * @property $this|bool|\Carbon\Carbon|\DateTime|mixed|static category_type
 */
class Category extends Model
{

    use SearchableTrait;

    /**
     * The database connection
     */

    protected $connection = 'mysql';

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'category';
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_title',
        'category_type',
        'category_slug',
        'category_active'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];



    protected $searchable = [
        'columns' => [
            'category_title' => 10,
            'category_type' => 10,
            'category_slug' => 2
        ]
    ];

    public function relationships() {
        return $this->hasMany('APPPATH\Models\Properties\Properties_relation');
    }

    protected $guarded = ['category_id'];

    protected $primaryKey = 'category_id';

}

**Comment by giwrgos88** [comment]
Yes is inside app/Models/Categories/Category.php
Here is the model

< ? php namespace APPPATH\Models\Categories;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Nicolaslopezj\Searchable\SearchableTrait;

/**
 * @property $this|bool|\Carbon\Carbon|\DateTime|mixed|static category_type
 */
class Category extends Model
{

    use SearchableTrait;

    /**
     * The database connection
     */

    protected $connection = 'mysql';

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'category';
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_title',
        'category_type',
        'category_slug',
        'category_active'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];



    protected $searchable = [
        'columns' => [
            'category_title' => 10,
            'category_type' => 10,
            'category_slug' => 2
        ]
    ];

    public function relationships() {
        return $this->hasMany('APPPATH\Models\Properties\Properties_relation');
    }

    protected $guarded = ['category_id'];

    protected $primaryKey = 'category_id';

}

**Comment by tortuetorche** [comment]
Your Category controller is in a sub namespace (`Administrator`), so you need to config the `loadAndAuthorizeResource()` method inside your controller constructor to set the full path of your Category model.

Something like that:
```php
$this->loadAndAuthorizeResource(['class' => 'APPPATH\Models\Categories']);
```

You can read this [Wiki doc section](https://github.com/efficiently/authority-controller/wiki/Authorizing-controller-actions#custom-class) for more informations.

For the Dashboard controller it's a little bit different, because you don't have a Dashboard model.
So you can associate the Category model with it or use manual authorizations check, you can read the first paragraph of this [Wiki doc page](https://github.com/efficiently/authority-controller/wiki/Authorizing-controller-actions) for more informations

**Comment by giwrgos88** [comment]
@tortuetorche thanks a lot I will give a try!

**Comment by giwrgos88** [comment]
one last question and i will close the issue, if i want to define authority rules for specific controllers how i will write for example Category controller?
let say the category controller is has class name CategoryController and file name CategoryController.php and is stored inside App/Http/Controllers/Administrator/Category

so the rule will be 
$authority->allow(['read', 'create', 'update', 'destroy'], ['CategoryController']);

or I have to specify any special path?

Btw if i have a specific function inside the CategoryController like displayall_categories

I will use the addAlias to specify the function name?

**Comment by tortuetorche** [comment]
> so the rule will be
> `$authority->allow(['read', 'create', 'update', 'destroy'], ['CategoryController']);`
> or I have to specify any special path?

In your authorization rule, you should use the Category model instead of the Category controller.

> Btw if i have a specific function inside the CategoryController like displayall_categories
> I will use the addAlias to specify the function name?

For your custom Controller action you can read [this](https://github.com/efficiently/authority-controller/wiki/Authorizing-controller-actions#choosing-actions).

**Comment by tortuetorche** [comment]
I'm closing this issue, feel free to reopen it if you have bugs.

**Comment by giwrgos88** [comment]
I found something. when you pass the model class into the loadAndAuthorizeResource and the model has underscore for example Category_Model the loadAndAuthorizeResource is trying to load CategoryModel , instead of Category_Model.

Last questions the authorize function inside to each request form is affected from the library? I mean because I'm using your library to control the actions of each user the authorize function must be always true right? Because now it says that i don't have permission for editing a user but on the authority-controller I have $authority->allow('manage', 'all');

**Comment by tortuetorche** [comment]
Why your model names have underscores? You should follow the [PSR-2 coding style guide](http://www.php-fig.org/psr/psr-2) and name your class only in StudlyCaps format.

When you said _request form_ you means Laravel's [Form Request Validation](http://laravel.com/docs/5.0/validation#form-request-validation)?

**Comment by giwrgos88** [comment]
@tortuetorche yes i know the coding style but because in order for some people to understand that the model is related to a specific table which has the same name i had to use the underscore. Yes the form request validation

**Comment by tortuetorche** [comment]
The `authorize()` method of `FormRequest` objects are not related to Authority-Controller, it's another way to check authorizations in your Laravel 5 application.

You should not use the Laravel's Form Request authorization system with Authority-Controller.

Here what say the Laravel doc:
> If you plan to have authorization logic in another part of your application, simply return true from the `authorize` method
```php
/**
 * Determine if the user is authorized to make this request.
 *
 * @return bool
 */
public function authorize()
{
    return true;
}
```

**Comment by giwrgos88** [comment]
Ok I this is what i did. Thanks a lot for your help and time

**Comment by tortuetorche** [comment]
> in order for some people to understand that the model is related to a specific table which has the same name i had to use the underscore. Yes the form request validation

You can set a custom table name in your Model class. Here the Laravel doc:
> Note that we did not tell Eloquent which table to use for our User model. The "snake case" name of the class will be used as the table name unless another name is explicitly specified. So, in this case, Eloquent will assume the User model stores records in the users table. You may specify a custom table by defining a table property on your model:
```php
class User extends Model
{
    protected $table = 'my_users';
}
```

**Comment by giwrgos88** [comment]
Yes this is what i did after all. I removed all the underscores from the models who had underscore. Thanks a lot for your help, once more!!

**Comment by tortuetorche** [comment]
You're welcome, have a good week-end!

**Comment by giwrgos88** [comment]
@tortuetorche you too!
