### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by RomainLanz** [efficiently/authority-controller#24]
Hey,

you didn't tag a new release for the 2.0. Can you do that or are you waiting the update of machuga package?

**Comment by RomainLanz** [comment]
And if I use `2.0.*@dev` I got this error:

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for efficiently/authority-controller 2.0.*@dev -> satisfiable by efficiently/authority-controller[2.0.x-dev].
    - efficiently/authority-controller 2.0.x-dev requires stayallive/authority-l5 ~2.4.1 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by tortuetorche** [comment]
Hi Romain,

> you didn't tag a new release for the 2.0. Can you do that or are you waiting the update of machuga package?

I wait for @machuga package update then I'll release a _stable_ version of Authority-Controller 2.0. But it doesn't mean it's unstable, you can used it in production.

For your error, read this, please:
https://github.com/efficiently/authority-controller/issues/19#issuecomment-82201011

Cheers,
Tortue Torche

**Comment by RomainLanz** [comment]
Thanks for your quick answer! :+1:
