### ISSUE TITLE
error adding authority-controller 

### ISSUE THREAD

**Issue by smicroz** [efficiently/authority-controller#25]
$ composer require efficiently/authority-controller:2.0.*

return

Problem 1
- Installation request for efficiently/authority-controller 2.0.* -> satisfiable by efficiently/authority-controller[2.0.x-dev].
- efficiently/authority-controller 2.0.x-dev requires stayallive/authority-l5 ~2.4.1 -> no matching package found.

**Comment by tortuetorche** [comment]
For your error, read this, please:
https://github.com/efficiently/authority-controller/issues/19#issuecomment-82201011
