### ISSUE TITLE
Mimic "pages ownership, publishing, ..."

### ISSUE THREAD

**Issue by cgrisar** [efficiently/authority-controller#26]
Hi,

I want to create a site where every user owns his page and possibly subpages.
An owner can publish and moderate on his page.
A member of a page can publish, delete and edit his own posts

Is authority a good plugin to implement that kind of features?
How would I do that?

Thanks,

Charles

**Comment by tortuetorche** [comment]
Hi @cgrisar,

Of course you can use Authority-Controller for your project.
You should read this [Wiki section](https://github.com/efficiently/authority-controller/wiki/Defining-Authority-rules#defining-authority-rules-with-closures-conditional-callbacks) then you should read the others Wiki doc pages :wink:

Cheers,
Tortue Torche
