### ISSUE TITLE
L5: When using the config cache: PHP Fatal error:  Call to undefined method Closure::__set_state()

### ISSUE THREAD

**Issue by d-a-n** [efficiently/authority-controller#27]
The config file should not contain a closure since this will throw `PHP Fatal error:  Call to undefined method Closure::__set_state()` when the config cache is enabled.

Edit: same problem for the route cache:
    
    [LogicException]
    Unable to prepare route [oauth/authorize] for serialization. Uses Closure.

//cc @TUNER88

**Comment by tortuetorche** [comment]
I need to check this, I found a similar issue with the `OAuth Server for Laravel` package: 
https://github.com/lucadegasperi/oauth2-server-laravel/issues/323

**Comment by tortuetorche** [comment]
Hi @d-a-n,

Can you update your Laravel 5 application and edit your `config/authority-controller.php` with these changes:

```php
<?php

$serializer = new SuperClosure\Serializer;
return [
    'initialize' => $serializer->serialize(function ($authority) {
        // Your authorization rules...
    })
];
```

If it works for you, I'll close this issue.

NB: You should clear the cache of your application before doing anything.
And remove the `vendor/config.php` file.
 
Have a good day,
Tortue Torche

**Comment by tortuetorche** [comment]
@d-a-n Can I close this issue?

**Comment by tortuetorche** [comment]
@d-a-n If you still encounter this bug, feel free to reopen this issue.
