### ISSUE TITLE
The authorization does not work as expected.

### ISSUE THREAD

**Issue by bamboowebcare** [efficiently/authority-controller#29]
The authorization does not work as expected.
An index page on wich I want to show only documents that belong to the current user:
___
 else if($user->hasRole('user')) {

        $authority->allow('read', 'App\Document', function ($self, $document) { 
           return $document->active === true && $self->user()->id === $document->user_id;
        });
    }
____
Looks just like the project example in the docs, but it does nothing. I just get all documents from all users.

What to do next?

**Comment by tortuetorche** [comment]
> An index page

You mean an `index` action?
For `index` action you should read these Wiki sections:
1. https://github.com/efficiently/authority-controller/wiki/Checking-Authority-rules#for-laravel-50
2. https://github.com/efficiently/authority-controller/wiki/Defining-Authority-rules#only-for-object-attributes
3. https://github.com/efficiently/authority-controller/wiki/Authorizing-controller-actions#index-action

**Comment by tortuetorche** [comment]
You can manually check authorizations of your controller actions with the `authorize()` method.
```php
public function index()
{
    foreach($this->documents as $document) {
        $this->authorize('read', $document); // Manual check
    }
}
```

Or in your model with the `Authority::authorize()` method, e.g. inside a [query scope](http://laravel.com/docs/5.0/eloquent#query-scopes).

**Comment by tortuetorche** [comment]
Hi @bamboowebcare,

I close this issue, feel free to reopen it if you have any problems.

Cheers,
Tortue Torche.
