### ISSUE TITLE
Laravel 5.2 Exception Macroable.php line 81: Method filter does not exist.

### ISSUE THREAD

**Issue by psdtohtmlcloud** [efficiently/authority-controller#32]
BadMethodCallException in Macroable.php line 81: 
Error : Method filter does not exist.

http://stackoverflow.com/questions/34973173/method-filter-does-not-exist-error-in-laravel
https://laravel.com/docs/master/middleware

Thanks
Vaibhav

**Comment by tortuetorche** [comment]
Hi @psdtohtmlcloud,

Thank you for reporting this issue :+1:
Bu I can't help you if you don't give me more information.
What version of `authority-controller` are you using?
Because only the last version support Laravel 5.2

So be sure to have this line in your `composer.json` file:
```json
"efficiently/authority-controller": "~2.2.0",
```

Then you can run this command in your terminal:
```bash
composer update efficiently/authority-controller
```

If the issue still occurs, can you send me the complete stack trace of your error, please?

Cheers,
Tortue Torche

**Comment by psdtohtmlcloud** [comment]
Hi tortuetorche
after following your instruction getting below error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package efficiently/authority-controller could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by psdtohtmlcloud** [comment]
Hi
In demo app with laravel 5.2 ver.

https://raw.githubusercontent.com/efficiently/laravel_authority-controller_app/master/composer.json
contains
"efficiently/authority-controller": "2.2.*"

but 

2.2.* branch doesn't exist & your master & dev-branch doesn't support laravel 5.2

**Comment by tortuetorche** [comment]
I see.
You need to add this line, at the end of your `composer.json` file:
```json
  "minimum-stability": "dev"
```

Here a sample of a valid `composer.json` file with `authority-controller` 2.2:
https://github.com/efficiently/laravel_authority-controller_app/blob/6b07f04b1ac51efa01ae5b1649de5c6d21e02df2/composer.json

**Comment by psdtohtmlcloud** [comment]
Hi tortuetorche
Earlier it was not working with
"efficiently/authority-controller": "dev-master"

might be you have commited something to dev-master branch
right now it is working with dev-master

but if you create branch ~2.2.0 that would be great.
because  "dev-master" must be for development & testing purpose.

Thanks! for your response.

**Comment by tortuetorche** [comment]
> but if you create branch ~2.2.0 that would be great.

I plan to create a tag `2.2.0` tag but I need more feedback.
If your Laravel application works well with the `master` branch (the `2.2` branch is an alias on the `master` one). I'll do it sooner.

So I'll wait your answer to create the tag and close this issue.

**Comment by psdtohtmlcloud** [comment]
My application is working with "dev-master" branch.
Not with "master"
Sure you can create tag 2.2.0 later.Thanks for information.

But please add instructions in readme for Laravel 5.2
It can help other.

and i have just started using your package.
you have mentioned that you are following cancan for authorization. that i love about your package.

Hoping it was awesome like cancan.
Thanks

**Comment by psdtohtmlcloud** [comment]
If you want me to test it with master branch or after creating 2.2.0 branch then let me know
I will glad to let you know.
:)

**Comment by tortuetorche** [comment]
FYI, the Composer `dev-master` branch is the git `master` branch.
> If you want me to test it with master branch

Yes, please.

**Comment by psdtohtmlcloud** [comment]
Hi tortuetorche
It works.I just checked your composer.json file and aliases.
You can push your tag if you want.
Thanks
