### ISSUE TITLE
[2.1] High memory usage

### ISSUE THREAD

**Issue by Zilurex** [efficiently/authority-controller#33]
Hello,
I've encountered following issue. I've got about 400k records in table and paginates it. Meanwhile `$this->loadResource();` in ControllerResource  generates above 300MB memory usage what is huge problem for me.

**Comment by tortuetorche** [comment]
Hi @Zilurex,

Thank you for reporting this issue, but I need more information to help you.
Can you tell me for which action your `$this->loadResource();` is used? A collection action (`index`, `search`) or a member action (`show`, `edit`...)?
If you have SQL logs it'll be helpful too.

And you can read [this Wiki section](https://github.com/efficiently/authority-controller/wiki/Authorizing-controller-actions#index-action) to use a scope who limit the number of the records return by the SQL query, generated by authority-controller.
 
Cheers,
Tortue Torche

**Comment by Zilurex** [comment]
Thank you for fast answer @tortuetorche ,

Action is index, currently I followed your advice and created scope to limit records. It works but now limit per page is static, however I'm not sure if it is possible to fetch current limit in model.
Here is my scope:
`	public function scopePaginated($query)
	{
		$query->limit(10);
	}`

`$this->getPerPage()` returns default value (15).

Best wishes,
Zilurex

**Comment by tortuetorche** [comment]
In your controller can you try something like that:
```php
$this->loadAndAuthorizeResource(['collectionScope' => ['scopePaginated', $this->getPerPage()]]); // will use Product::paginated(15)->get();
```

**Comment by tortuetorche** [comment]
Otherwise, You can use the authorize method to manually handle authorization in a controller action. This will raise an `Efficiently\AuthorityController\Exceptions\AccessDenied` exception when the user does not have permission.

```php
public function index()
{
    $this->authorize('index', Project::class);
    $this->projects = Project::limit($this->getPerPage())->get();
}
```

**Comment by Zilurex** [comment]
Works just fine.
Thank you for your trouble.

**Comment by tortuetorche** [comment]
Glad to resolve your issue :smile: 
And of course  when you manually handle authorization in a controller action, you should except this action in your `loadResource()` or `loadAndAuthorizeResource()` method, like this:

```php
$this->loadAndAuthorizeResource(['except' => ['index']]);
```

**Comment by tortuetorche** [comment]
@Zilurex I'm going to close this issue, feel free to reopen it, if you have any problems.

Have a good day :sunglasses:,
Tortue Torche
